name= "Provide your profile through the following questions from below:"
print ("\033[1m" + name + "\033[0m")

name1 = input(" Enter your Name : ")
name2 = input ( "Enter your Age :")
name3 = input ( "Enter your Sex :")
name4 = input ( "Enter your Birthday :")
name5 = input ( "Enter your Country :")
name6 = input ( "Enter University Name :")
name7 = input ( "Enter your Education Level :")
name8 = input ( "Enter Marital Status :")
name9 = input ( "Enter your Favorite Hobby to do :")
name10 = input (" Enter your Favorite Artist :")
print (name1)
print (name2)
print (name3)
print (name4)
print (name5)
print (name6)
print (name7)
print (name8)
print (name9)
print (name10)

